services:
  backend:
    build: .
    command: make run
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - EMAIL_HOST=smtp4dev
      - EMAIL_PORT=25
    ports:
      - "8000:8000"

  worker:
    build: .
    command: uv run celery -A config worker -l INFO
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - EMAIL_HOST=smtp4dev
      - EMAIL_PORT=25

  redis:
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"

  smtp4dev:
    image: rnwood/smtp4dev:3.7.0-ci20250120116
    ports:
      - "5000:80"  # Web UI
      - "2525:25"
